project:
  max_generations: 10
agent:
  max_steps: 30
search:
  seed: 0
  exploration_rate: 0.2
  branch_factor: 2
evaluation:
  games: 5
  realtime: false
  map: AbyssalReefLE
  bot_race: Terran
  opponent:
    race: Terran
    difficulty: CheatVision
    build: RandomBuild
  game_timeout_sec: 1800
tools:
  bash_timeout_sec: 60
